-- ============================================================
-- Migration 002: Reference tables for Pronounce feature
-- ============================================================

-- ── phoneme_reference ──────────────────────────────────────────
-- Static list of phonemes per language (no RLS — public reference data)
create table phoneme_reference (
  id       uuid primary key default gen_random_uuid(),
  language text not null check (language in ('en','fr')),
  phoneme  text not null,
  label    text,           -- human-readable e.g. "Short I (bit)"
  unique (language, phoneme)
);

-- English phonemes (IPA)
insert into phoneme_reference (language, phoneme, label) values
  -- Vowels
  ('en', 'iː',  'Long EE (see)'),
  ('en', 'ɪ',   'Short I (bit)'),
  ('en', 'e',   'Short E (bed)'),
  ('en', 'æ',   'Short A (cat)'),
  ('en', 'ɑː',  'Long A (father)'),
  ('en', 'ɒ',   'Short O (hot)'),
  ('en', 'ɔː',  'Long AW (law)'),
  ('en', 'ʊ',   'Short U (book)'),
  ('en', 'uː',  'Long OO (food)'),
  ('en', 'ʌ',   'Short U (cup)'),
  ('en', 'ɜː',  'ER (bird)'),
  ('en', 'ə',   'Schwa (about)'),
  -- Diphthongs
  ('en', 'eɪ',  'AY (day)'),
  ('en', 'aɪ',  'I (my)'),
  ('en', 'ɔɪ',  'OY (boy)'),
  ('en', 'əʊ',  'OH (go)'),
  ('en', 'aʊ',  'OW (now)'),
  ('en', 'ɪə',  'EAR (ear)'),
  ('en', 'eə',  'AIR (hair)'),
  ('en', 'ʊə',  'URE (cure)'),
  -- Consonants
  ('en', 'p',   'P (pen)'),
  ('en', 'b',   'B (bed)'),
  ('en', 't',   'T (ten)'),
  ('en', 'd',   'D (dog)'),
  ('en', 'k',   'K (cat)'),
  ('en', 'g',   'G (get)'),
  ('en', 'f',   'F (fat)'),
  ('en', 'v',   'V (van)'),
  ('en', 'θ',   'TH unvoiced (think)'),
  ('en', 'ð',   'TH voiced (this)'),
  ('en', 's',   'S (sun)'),
  ('en', 'z',   'Z (zoo)'),
  ('en', 'ʃ',   'SH (ship)'),
  ('en', 'ʒ',   'ZH (measure)'),
  ('en', 'h',   'H (hat)'),
  ('en', 'tʃ',  'CH (chip)'),
  ('en', 'dʒ',  'J (judge)'),
  ('en', 'm',   'M (man)'),
  ('en', 'n',   'N (no)'),
  ('en', 'ŋ',   'NG (sing)'),
  ('en', 'l',   'L (leg)'),
  ('en', 'r',   'R (red)'),
  ('en', 'j',   'Y (yes)'),
  ('en', 'w',   'W (wet)'),
  -- French phonemes
  ('fr', 'i',   'I (fille)'),
  ('fr', 'e',   'É (été)'),
  ('fr', 'ɛ',   'È (fête)'),
  ('fr', 'a',   'A (patte)'),
  ('fr', 'ɑ',   'Â (pâte)'),
  ('fr', 'ɔ',   'O ouvert (or)'),
  ('fr', 'o',   'O fermé (eau)'),
  ('fr', 'u',   'OU (ou)'),
  ('fr', 'y',   'U (tu)'),
  ('fr', 'ø',   'EU fermé (feu)'),
  ('fr', 'œ',   'EU ouvert (peur)'),
  ('fr', 'ə',   'E caduc (le)'),
  ('fr', 'ɛ̃',  'IN (fin)'),
  ('fr', 'ɑ̃',  'AN (dans)'),
  ('fr', 'ɔ̃',  'ON (bon)'),
  ('fr', 'œ̃',  'UN (brun)'),
  ('fr', 'j',   'Y (yeux)'),
  ('fr', 'w',   'OI (oui)'),
  ('fr', 'ɥ',   'UI (nuit)'),
  ('fr', 'p',   'P (père)'),
  ('fr', 'b',   'B (beau)'),
  ('fr', 't',   'T (table)'),
  ('fr', 'd',   'D (dos)'),
  ('fr', 'k',   'K (café)'),
  ('fr', 'g',   'G (gare)'),
  ('fr', 'f',   'F (feu)'),
  ('fr', 'v',   'V (vin)'),
  ('fr', 's',   'S (sol)'),
  ('fr', 'z',   'Z (zéro)'),
  ('fr', 'ʃ',   'CH (chat)'),
  ('fr', 'ʒ',   'J (jour)'),
  ('fr', 'm',   'M (mer)'),
  ('fr', 'n',   'N (nez)'),
  ('fr', 'ɲ',   'GN (agneau)'),
  ('fr', 'ŋ',   'NG (camping)'),
  ('fr', 'l',   'L (lune)'),
  ('fr', 'r',   'R (rue)');

-- ── phoneme_example_words ──────────────────────────────────────
create table phoneme_example_words (
  id       uuid primary key default gen_random_uuid(),
  language text not null check (language in ('en','fr')),
  phoneme  text not null,
  word     text not null,
  unique (language, phoneme)
);

-- English example words per phoneme
insert into phoneme_example_words (language, phoneme, word) values
  ('en', 'iː',  'see'),
  ('en', 'ɪ',   'bit'),
  ('en', 'e',   'bed'),
  ('en', 'æ',   'cat'),
  ('en', 'ɑː',  'father'),
  ('en', 'ɒ',   'hot'),
  ('en', 'ɔː',  'law'),
  ('en', 'ʊ',   'book'),
  ('en', 'uː',  'food'),
  ('en', 'ʌ',   'cup'),
  ('en', 'ɜː',  'bird'),
  ('en', 'ə',   'about'),
  ('en', 'eɪ',  'day'),
  ('en', 'aɪ',  'my'),
  ('en', 'ɔɪ',  'boy'),
  ('en', 'əʊ',  'go'),
  ('en', 'aʊ',  'now'),
  ('en', 'ɪə',  'ear'),
  ('en', 'eə',  'hair'),
  ('en', 'ʊə',  'cure'),
  ('en', 'p',   'pen'),
  ('en', 'b',   'bed'),
  ('en', 't',   'ten'),
  ('en', 'd',   'dog'),
  ('en', 'k',   'cat'),
  ('en', 'g',   'get'),
  ('en', 'f',   'fat'),
  ('en', 'v',   'van'),
  ('en', 'θ',   'think'),
  ('en', 'ð',   'this'),
  ('en', 's',   'sun'),
  ('en', 'z',   'zoo'),
  ('en', 'ʃ',   'ship'),
  ('en', 'ʒ',   'measure'),
  ('en', 'h',   'hat'),
  ('en', 'tʃ',  'chip'),
  ('en', 'dʒ',  'judge'),
  ('en', 'm',   'man'),
  ('en', 'n',   'no'),
  ('en', 'ŋ',   'sing'),
  ('en', 'l',   'leg'),
  ('en', 'r',   'red'),
  ('en', 'j',   'yes'),
  ('en', 'w',   'wet'),
  -- French example words
  ('fr', 'i',   'fille'),
  ('fr', 'e',   'été'),
  ('fr', 'ɛ',   'fête'),
  ('fr', 'a',   'patte'),
  ('fr', 'ɑ',   'pâte'),
  ('fr', 'ɔ',   'or'),
  ('fr', 'o',   'eau'),
  ('fr', 'u',   'ou'),
  ('fr', 'y',   'tu'),
  ('fr', 'ø',   'feu'),
  ('fr', 'œ',   'peur'),
  ('fr', 'ə',   'le'),
  ('fr', 'ɛ̃',  'fin'),
  ('fr', 'ɑ̃',  'dans'),
  ('fr', 'ɔ̃',  'bon'),
  ('fr', 'œ̃',  'brun'),
  ('fr', 'j',   'yeux'),
  ('fr', 'w',   'oui'),
  ('fr', 'ɥ',   'nuit'),
  ('fr', 'p',   'père'),
  ('fr', 'b',   'beau'),
  ('fr', 't',   'table'),
  ('fr', 'd',   'dos'),
  ('fr', 'k',   'café'),
  ('fr', 'g',   'gare'),
  ('fr', 'f',   'feu'),
  ('fr', 'v',   'vin'),
  ('fr', 's',   'sol'),
  ('fr', 'z',   'zéro'),
  ('fr', 'ʃ',   'chat'),
  ('fr', 'ʒ',   'jour'),
  ('fr', 'm',   'mer'),
  ('fr', 'n',   'nez'),
  ('fr', 'ɲ',   'agneau'),
  ('fr', 'ŋ',   'camping'),
  ('fr', 'l',   'lune'),
  ('fr', 'r',   'rue');
